server:
  port: 8080
spring:
  application:
    name: PDF
# pdf配置
pdf:
  # fop配置文件路径
  conf: E:/Workspace/project-advice/zero-one-08mes/mes-java/mes-sample-pdf/src/main/resources/fop.xconf
  # xsl-fo模板路径（目录）
  template: E:/Workspace/project-advice/zero-one-08mes/mes-java/mes-sample-pdf/src/main/resources/freemarker